#pragma once
#ifndef __INCLUDE_RESOURCE_STRING_ID_H__
#define __INCLUDE_RESOURCE_STRING_ID_H__

#include "CalculatorManagerLibNS.h"

CM_BEGIN

#define RES_STR inline constexpr const char*
RES_STR RS_NUM_0 = "NUM_0";
RES_STR RS_NUM_1 = "NUM_1";
RES_STR RS_NUM_2 = "NUM_2";
RES_STR RS_NUM_3 = "NUM_3";
RES_STR RS_NUM_4 = "NUM_4";
RES_STR RS_NUM_5 = "NUM_5";
RES_STR RS_NUM_6 = "NUM_6";
RES_STR RS_NUM_7 = "NUM_7";
RES_STR RS_NUM_8 = "NUM_8";
RES_STR RS_NUM_9 = "NUM_9";
RES_STR RS_NUM_A = "NUM_A";
RES_STR RS_NUM_B = "NUM_B";
RES_STR RS_NUM_C = "NUM_C";
RES_STR RS_NUM_D = "NUM_D";
RES_STR RS_NUM_E = "NUM_E";
RES_STR RS_NUM_F = "NUM_F";

RES_STR RS_ADD = "ADD";
RES_STR RS_SUB = "SUB";
RES_STR RS_MUL = "MUL";
RES_STR RS_DIV = "DIV";
RES_STR RS_REM = "REM";
RES_STR RS_MOD = "MOD";
RES_STR RS_LSHA = "LSHA";
RES_STR RS_LSHL = "LSHL";
RES_STR RS_RSHA = "RSHA";
RES_STR RS_RSHL = "RSHL";
RES_STR RS_AND = "AND";
RES_STR RS_OR = "OR";
RES_STR RS_XOR = "XOR";
RES_STR RS_NAND = "NAND";
RES_STR RS_NOR = "NOR";
RES_STR RS_PWR = "PWR";
RES_STR RS_YROOT = "YROOT";
RES_STR RS_LOGBASEY = "LOGBASEY";

RES_STR RS_ROR = "ROR";
RES_STR RS_ROL = "ROL";
RES_STR RS_RORC = "RORC";
RES_STR RS_ROLC = "ROLC";
RES_STR RS_NOT = "NOT";
RES_STR RS_DMS = "DMS";
RES_STR RS_DEGREE = "DEGREE";
RES_STR RS_FRAC = "FRAC";
RES_STR RS_INT = "INT";
RES_STR RS_SIN_DEG = "SIN_DEG";
RES_STR RS_SIN_RAD = "SIN_RAD";
RES_STR RS_SIN_GRAD = "SIN_GRAD";
RES_STR RS_COS_DEG = "COS_DEG";
RES_STR RS_COS_RAD = "COS_RAD";
RES_STR RS_COS_GRAD = "COS_GRAD";
RES_STR RS_TAN_DEG = "TAN_DEG";
RES_STR RS_TAN_RAD = "TAN_RAD";
RES_STR RS_TAN_GRAD = "TAN_GRAD";
RES_STR RS_SINH = "SINH";
RES_STR RS_COSH = "COSH";
RES_STR RS_TANH = "TANH";
RES_STR RS_ARCSIN_DEG = "ARCSIN_DEG";
RES_STR RS_ARCSIN_RAD = "ARCSIN_RAD";
RES_STR RS_ARCSIN_GRAD = "ARCSIN_GRAD";
RES_STR RS_ARCCOS_DEG = "ARCCOS_DEG";
RES_STR RS_ARCCOS_RAD = "ARCCOS_RAD";
RES_STR RS_ARCCOS_GRAD = "ARCCOS_GRAD";
RES_STR RS_ARCTAN_DEG = "ARCTAN_DEG";
RES_STR RS_ARCTAN_RAD = "ARCTAN_RAD";
RES_STR RS_ARCTAN_GRAD = "ARCTAN_GRAD";
RES_STR RS_ARSINH = "ARSINH";
RES_STR RS_ARCOSH = "ARCOSH";
RES_STR RS_ARTANH = "ARTANH";
RES_STR RS_SEC_DEG = "SEC_DEG";
RES_STR RS_SEC_RAD = "SEC_RAD";
RES_STR RS_SEC_GRAD = "SEC_GRAD";
RES_STR RS_CSC_DEG = "CSC_DEG";
RES_STR RS_CSC_RAD = "CSC_RAD";
RES_STR RS_CSC_GRAD = "CSC_GRAD";
RES_STR RS_COT_DEG = "COT_DEG";
RES_STR RS_COT_RAD = "COT_RAD";
RES_STR RS_COT_GRAD = "COT_GRAD";
RES_STR RS_SECH = "SECH";
RES_STR RS_CSCH = "CSCH";
RES_STR RS_COTH = "COTH";
RES_STR RS_ARCSEC_DEG = "ARCSEC_DEG";
RES_STR RS_ARCSEC_RAD = "ARCSEC_RAD";
RES_STR RS_ARCSEC_GRAD = "ARCSEC_GRAD";
RES_STR RS_ARCCSC_DEG = "ARCCSC_DEG";
RES_STR RS_ARCCSC_RAD = "ARCCSC_RAD";
RES_STR RS_ARCCSC_GRAD = "ARCCSC_GRAD";
RES_STR RS_ARCCOT_DEG = "ARCCOT_DEG";
RES_STR RS_ARCCOT_RAD = "ARCCOT_RAD";
RES_STR RS_ARCCOT_GRAD = "ARCCOT_GRAD";
RES_STR RS_ARSECH = "ARSECH";
RES_STR RS_ARCSCH = "ARCSCH";
RES_STR RS_ARCOTH = "ARCOTH";
RES_STR RS_LN = "LN";
RES_STR RS_LOG = "LOG";
RES_STR RS_INV = "INV";
RES_STR RS_SQU = "SQU";
RES_STR RS_SQRT = "SQRT";
RES_STR RS_CUB = "CUB";
RES_STR RS_CUBT = "CUBT";
RES_STR RS_PWR10 = "PWR10";
RES_STR RS_PWR2 = "PWR2";
RES_STR RS_PWRE = "PWRE";
RES_STR RS_PERCENT = "PERCENT";
RES_STR RS_ABS = "ABS";
RES_STR RS_FLOOR = "FLOOR";
RES_STR RS_CEIL = "CEIL";
RES_STR RS_NEG = "NEG";

RES_STR RS_EXP = "EXP";
RES_STR RS_LSH = "LSH";
RES_STR RS_RSH = "RSH";
RES_STR RS_SHA = "SHA";
RES_STR RS_SHL = "SHL";
RES_STR RS_ROSH = "ROSH";
RES_STR RS_RCSH = "RCSH";
RES_STR RS_CLEAR = "CLEAR";
RES_STR RS_CENTR = "CENTR";
RES_STR RS_BACK = "BACK";
RES_STR RS_OPENP = "OPENP";
RES_STR RS_CLOSEP = "CLOSEP";
RES_STR RS_EQU = "EQU";
RES_STR RS_PNT = "PNT";
RES_STR RS_SIGN = "SIGN";
RES_STR RS_MSTORE = "MSTORE";
RES_STR RS_MRECALL = "MRECALL";
RES_STR RS_MPLUS = "MPLUS";
RES_STR RS_MMINUS = "MMINUS";
RES_STR RS_MCLEAR = "MCLEAR";
RES_STR RS_BIN = "BIN";
RES_STR RS_OCT = "OCT";
RES_STR RS_DEC = "DEC";
RES_STR RS_HEX = "HEX";
RES_STR RS_BYTE = "BYTE";
RES_STR RS_WORD = "WORD";
RES_STR RS_DWORD = "DWORD";
RES_STR RS_QWORD = "QWORD";
RES_STR RS_DEG = "DEG";
RES_STR RS_RAD = "RAD";
RES_STR RS_GRAD = "GRAD";
RES_STR RS_FLOFMT = "FLOFMT";
RES_STR RS_SCIFMT = "SCIFMT";
RES_STR RS_ENGFMT = "ENGFMT";
RES_STR RS_STDMODE = "STDMODE";
RES_STR RS_SCIMODE = "SCIMODE";
RES_STR RS_PROMODE = "PROMODE";
RES_STR RS_INVC = "INVC";
RES_STR RS_HYP = "HYP";
RES_STR RS_SIN = "SIN";
RES_STR RS_COS = "COS";
RES_STR RS_TAN = "TAN";
RES_STR RS_SEC = "SEC";
RES_STR RS_CSC = "CSC";
RES_STR RS_COT = "COT";
RES_STR RS_PI = "PI";
RES_STR RS_EULER = "EULER";
RES_STR RS_RAND = "RAND";
RES_STR RS_SET_RET = "SET_RET";

RES_STR RS_CMD_NULL = "CMD_NULL";

RES_STR RS_MPL_ERR_INVALID_VAL = "MPL_ERR_INVALID_VAL";
RES_STR RS_MPL_ERR_OUT_OF_MEM = "MPL_ERR_OUT_OF_MEM";
RES_STR RS_MPL_ERR_MAX_ITER_REACHED = "MPL_ERR_MAX_ITER_REACHED";
RES_STR RS_MPL_ERR_BUF_OVERFLOW = "MPL_ERR_BUF_OVERFLOW";
RES_STR RS_MPL_ERR_UNKNOWN_ERR = "MPL_ERR_UNKNOWN_ERR";
RES_STR RS_MPL_ERR_RESULT_UNDEF = "MPL_ERR_RESULT_UNDEF";
RES_STR RS_MPL_ERR_DIV_BY_ZERO = "MPL_ERR_DIV_BY_ZERO";
RES_STR RS_MPL_ERR_RESULT_INF = "MPL_ERR_RESULT_INF";
RES_STR RS_MPL_ERR_NULL = "MPL_ERR_NULL";

RES_STR RS_CE_ERR_INPUT_OVERFLOW = "CE_ERR_INPUT_OVERFLOW";
RES_STR RS_CE_ERR_OUTPUT_OVERFLOW = "CE_ERR_OUTPUT_OVERFLOW";
RES_STR RS_CE_ERR_UNKNOW_NUM_REPRESENTATION = "CE_ERR_UNKNOW_NUM_REPRESENTATION";
RES_STR RS_CE_ERR_WRONG_OPERATOR_CODE = "CE_ERR_WRONG_OPERATOR_CODE";
RES_STR RS_CE_ERR_NULL = "CE_ERR_NULL";

RES_STR RS_GS_ERR_TOO_MANY_SC = "GS_ERR_TOO_MANY_SC";
RES_STR RS_GS_ERR_ILLEGAL_CH_EXIST = "GS_ERR_ILLEGAL_CH_EXIST";
RES_STR RS_GS_ERR_TOO_MANY_ZERO = "GS_ERR_TOO_MANY_ZERO";
RES_STR RS_GS_ERR_NOT_ZERO_AFTER_ZERO = "GS_ERR_NOT_ZERO_AFTER_ZERO";
RES_STR RS_GS_ERR_NULL = "GS_ERR_NULL";
#undef RES_STR
CM_END
#endif // !__INCLUDE_RESOURCE_STRING_ID_H__
